from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import *
from decimal import Decimal
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db import transaction
import random
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponse


def test_view(request):
    """Simple test view to check if the server is working"""
    return HttpResponse("CashG Bank is working! Server is running properly.")


@csrf_protect
def Login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if not username or not password:
            messages.error(request, 'Username and password are required.')
            return render(request, 'login.html')

        user = authenticate(request, username=username.strip(), password=password)

        if user is not None:
            login(request, user)
            return redirect('dashboard')
        else:
            messages.error(request, 'Oops! The username or password you entered is incorrect.')

    return render(request, 'login.html')


@login_required
def logout_view(request):
    logout(request)
    messages.success(request, 'You have been successfully logged out.')
    return redirect('login')


@login_required
def dashboard(request):
    try:
        account = Account.objects.get(user=request.user)
        recent_transactions = Transaction.objects.filter(account=account).order_by('-timestamp')[:5]
    except Account.DoesNotExist:
        messages.error(request, "Account not found. Please contact support.")
        return redirect('login')
    
    context = {
        'account': account,
        'recent_transactions': recent_transactions,
    }
    return render(request, 'dashboard.html', context)



@csrf_protect
@transaction.atomic
def signup(request):
    if request.method == 'POST':
        # Match the HTML form field names
        username = request.POST.get('username')
        account_type = request.POST.get('account_type')  # This gets 'Client' or 'Admin'
        password1 = request.POST.get('password')  # Changed to match HTML
        password2 = request.POST.get('confirm_password')  # Changed to match HTML
        
        # Validation
        if not all([username, account_type, password1, password2]):
            messages.error(request, "All fields are required.")
            return render(request, 'sign_up.html')
            
        if password1 != password2:
            messages.error(request, "Passwords do not match.")
            return render(request, 'sign_up.html')
            
        if account_type not in ['Admin', 'Client']:
            messages.error(request, "Invalid account type selected.")
            return render(request, 'sign_up.html')
            
        if User.objects.filter(username=username).exists():
            messages.error(request, "Username already exists.")
            return render(request, 'sign_up.html')
            
        if len(password1) < 8:
            messages.error(request, "Password must be at least 8 characters long.")
            return render(request, 'sign_up.html')
            
        try:
            # Create user
            user = User.objects.create_user(username=username, password=password1)
            
            # Create Account - map the account_type to model choices
            django_account_type = 'SAVINGS' if account_type == 'Client' else 'CHECKING'
            Account.objects.create(
                user=user,
                account_type=django_account_type
                # account_number will be auto-generated by the model
            )
            
            messages.success(request, "Account created successfully! You can now login.")
            return redirect('login')
            
        except Exception as e:
            messages.error(request, f"Error creating account: {str(e)}")
            return render(request, 'sign_up.html')
    
    return render(request, 'sign_up.html')

@login_required
@csrf_protect  
def deposit(request):
    try:
        # For GET requests, just get the account normally
        account = Account.objects.get(user=request.user)
    except Account.DoesNotExist:
        messages.error(request, "Account not found.")
        return redirect('dashboard')
    
    if request.method == 'POST':
        amount_str = request.POST.get('amount')
        description = request.POST.get('description', '')  # Get optional description
        
        try:
            amount = Decimal(amount_str)
            if amount >= 1.00:
                # Use transaction.atomic() for the POST operation
                with transaction.atomic():
                    # Now use select_for_update inside the transaction
                    account = Account.objects.select_for_update().get(user=request.user)
                    account.balance += amount
                    account.save()
                    
                    # Create transaction record with custom description if provided
                    transaction_description = description if description.strip() else f'Deposit to {account.account_type} account'
                    
                    Transaction.objects.create(
                        account=account,
                        amount=amount,
                        transaction_type='DEPOSIT',
                        description=transaction_description
                    )
                
                messages.success(request, f"Successfully deposited ₱{amount:,.2f}.")
                return redirect('dashboard')
            else:
                messages.error(request, "Amount must be at least ₱1.00.")
        except (ValueError, TypeError, Decimal.InvalidOperation):
            messages.error(request, "Invalid amount format. Please enter a valid number.")
        except Account.DoesNotExist:
            messages.error(request, "Account not found during transaction.")
            return redirect('dashboard')
    
    return render(request, 'deposit.html', {'account': account})

@login_required
@csrf_protect
def withdraw(request):
    # For GET requests, we don't need select_for_update
    if request.method == 'GET':
        try:
            account = Account.objects.get(user=request.user)
        except Account.DoesNotExist:
            messages.error(request, "Account not found.")
            return redirect('dashboard')
        return render(request, 'withdraw.html', {'account': account})
    
    # For POST requests, we need select_for_update inside a transaction
    elif request.method == 'POST':
        amount_str = request.POST.get('amount')
        description = request.POST.get('description', '')
        
        try:
            amount = Decimal(amount_str)
            
            # Validate amount range
            if not (200.00 <= amount <= 50000.00):
                messages.error(request, "Withdrawal must be between ₱200 and ₱50,000.")
                # Get account for re-rendering the form
                account = Account.objects.get(user=request.user)
                return render(request, 'withdraw.html', {'account': account})
            
            # Use atomic transaction for the withdrawal
            with transaction.atomic():
                account = Account.objects.select_for_update().get(user=request.user)
                
                # Check sufficient balance
                if amount > account.balance:
                    messages.error(request, "Insufficient balance.")
                    return render(request, 'withdraw.html', {'account': account})
                
                # Process withdrawal
                account.balance -= amount
                account.save()
                
                # Create transaction record
                Transaction.objects.create(
                    account=account,
                    amount=amount,
                    transaction_type='WITHDRAWAL',
                    description=description if description else f'Withdrawal from {account.account_type} account'
                )
                
            messages.success(request, f"Successfully withdrew ₱{amount:,.2f}.")
            return redirect('dashboard')
            
        except Account.DoesNotExist:
            messages.error(request, "Account not found.")
            return redirect('dashboard')
        except (ValueError, TypeError, Decimal.InvalidOperation):
            messages.error(request, "Invalid amount format.")
            # Get account for re-rendering the form
            try:
                account = Account.objects.get(user=request.user)
                return render(request, 'withdraw.html', {'account': account})
            except Account.DoesNotExist:
                return redirect('dashboard')


from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.db import transaction
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from decimal import Decimal

@login_required
@csrf_protect
def transfer(request):
    # Get account without select_for_update for GET requests
    try:
        account = Account.objects.get(user=request.user)
    except Account.DoesNotExist:
        messages.error(request, "Account not found.")
        return redirect('dashboard')
    
    if request.method == 'POST':
        recipient_username = request.POST.get('recipient')
        amount_str = request.POST.get('amount')
        note = request.POST.get('note', '')
        
        try:
            amount = Decimal(amount_str)
        except (ValueError, TypeError, Decimal.InvalidOperation):
            messages.error(request, "Invalid amount.")
            return render(request, 'transfer.html', {'account': account})
        
        # Basic validation before entering transaction
        if not (200 <= amount <= 50000):
            messages.error(request, "Transfer amount must be between ₱200 and ₱50,000.")
            return render(request, 'transfer.html', {'account': account})
        
        try:
            recipient_user = User.objects.get(username=recipient_username)
        except User.DoesNotExist:
            messages.error(request, "Recipient user not found.")
            return render(request, 'transfer.html', {'account': account})
        
        if recipient_user == request.user:
            messages.error(request, "Cannot transfer to your own account.")
            return render(request, 'transfer.html', {'account': account})
        
        # Use atomic transaction with select_for_update
        try:
            with transaction.atomic():
                # Lock both accounts to prevent race conditions
                sender_account = Account.objects.select_for_update().get(user=request.user)
                try:
                    recipient_account = Account.objects.select_for_update().get(user=recipient_user)
                except Account.DoesNotExist:
                    messages.error(request, "Recipient account not found.")
                    return render(request, 'transfer.html', {'account': account})
                
                # Check balance after locking
                if amount > sender_account.balance:
                    messages.error(request, "Insufficient balance.")
                    return render(request, 'transfer.html', {'account': sender_account})
                
                # Perform the transfer
                sender_account.balance -= amount
                recipient_account.balance += amount
                sender_account.save()
                recipient_account.save()
                
                # Create transaction records
                Transaction.objects.create(
                    account=sender_account,
                    amount=amount,
                    description=f'Transfer to {recipient_username}: {note}' if note else f'Transfer to {recipient_username}',
                    transaction_type='TRANSFER'
                )
                Transaction.objects.create(
                    account=recipient_account,
                    amount=amount,
                    description=f'Received from {request.user.username}: {note}' if note else f'Received from {request.user.username}',
                    transaction_type='RECEIVED'
                )
                Transfer.objects.create(
                    sender_account=sender_account,
                    recipient_account=recipient_account,
                    amount=amount,
                    note=note
                )
                
            messages.success(request, f"Successfully transferred ₱{amount:,.2f} to {recipient_username}.")
            return redirect('dashboard')
            
        except Exception as e:
            messages.error(request, "Transfer failed. Please try again.")
            return render(request, 'transfer.html', {'account': account})
    
    return render(request, 'transfer.html', {'account': account})

@login_required
def history(request):
    try:
        account = Account.objects.get(user=request.user)
        transactions = Transaction.objects.filter(account=account).order_by('-timestamp')
    except Account.DoesNotExist:
        messages.error(request, "Account not found.")
        return redirect('dashboard')

    context = {
        'account': account,
        'transactions': transactions,
    }
    return render(request, 'transactions.html', context)


@login_required
def profile(request):
    # Get or create Account
    account, created = Account.objects.get_or_create(
        user=request.user,
        defaults={
            'account_number': f"ACC{request.user.id:06d}",
            'account_type': 'Savings',
            'balance': 0.00
        }
    )
    
    # Get or create Profile
    user_profile, created = Profile.objects.get_or_create(user=request.user)
    
    if request.method == 'POST':
        messages.success(request, "Profile updated successfully.")
        return redirect('profile')
    
    context = {
        'account': account,
        'profile': user_profile,
        'total_deposits': 0,
        'total_withdrawals': 0,
        'total_transfers': 0,
        'total_transactions': 0,
    }
    return render(request, 'profile.html', context)
